//! `ObjectEnvelope` v2 (`MN-103`): a deliberately opaque outer
//! storage-and-routing container. Everything a v1 [`crate::Object`]
//! exposes in cleartext — object type, author, device, timestamp,
//! sequence, links, signatures — lives inside AEAD-authenticated
//! ciphertext (a [`crate::private_object::PrivateObject`]) instead. The
//! outer envelope carries only what blind storage and retrieval actually
//! need: a version tag, an AEAD suite, an opaque routing tag, coarse
//! retention metadata, a nonce, and ciphertext.
//!
//! ## Disambiguation from v1
//!
//! A v1 [`crate::Object`]'s first encoded byte is always `1`
//! (`Object::from_bytes` rejects anything else). This module's first byte
//! is always [`ENVELOPE_VERSION`] (`2`), and [`ObjectEnvelopeV2::from_bytes`]
//! rejects anything else just as strictly — the version byte is the entire
//! disambiguation mechanism (no separate magic bytes are needed: neither
//! format has any other framing that could be ambiguous at offset 0).
//! **No parser ever falls back from one version to the other.**
//!
//! ## What this does not do
//!
//! This hides private application metadata from the object *schema*. It
//! does not hide source IP, timing, ciphertext length, or access-pattern
//! correlation across repeated retrievals of the same opaque route — that
//! is `mini-net`/relay/mix work (`docs/design/
//! privacy-cost-doctrine-parallel-execution-plan.md` lanes L2/L3), out of
//! scope here on purpose. Key distribution (how an authorized reader gets
//! the [`mini_crypto::AeadKey`] passed to [`ObjectEnvelopeV2::seal`]/
//! [`ObjectEnvelopeV2::open`]) is also out of scope — this type accepts an
//! already-established key, the same way `mini_bearer::Channel` accepts an
//! already-agreed key rather than negotiating one itself.

use mini_crypto::{AeadKey, AeadNonce, AeadSuite};

use crate::codec::{Reader, Writer};
use crate::error::{ObjectError, Result};
use crate::object::ObjectId;
use crate::private_object::PrivateObject;

/// This module's version byte — distinct from v1's `1` by construction.
pub const ENVELOPE_VERSION: u8 = 2;

/// Hard cap on ciphertext length before allocating, generous enough for
/// [`crate::MAX_PAYLOAD_BYTES`] plus a `PrivateObject`'s own framing
/// overhead and the AEAD tag.
const MAX_CIPHERTEXT_BYTES: usize = crate::MAX_PAYLOAD_BYTES + 4096;

/// An opaque, fixed-length routing/retrieval tag. Carries no semantic
/// meaning of its own — never a DID, object type, or human-readable
/// label. [`OpaqueRoute::random`] is this first version's only
/// constructor: a deterministic, scope-derived tag (so an authorized
/// reader can compute the same tag without being told it out of band) is
/// deferred, matching the source research's own fallback guidance —
/// inventing a new HMAC-shaped construction merely to preserve
/// deterministic lookup is explicitly not worth it in this lane.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct OpaqueRoute([u8; 32]);

impl OpaqueRoute {
    /// A fresh random route tag from OS entropy.
    pub fn random() -> Result<Self> {
        Ok(OpaqueRoute(
            mini_crypto::random_32().map_err(ObjectError::Crypto)?,
        ))
    }

    /// Build from already-generated bytes (e.g. round-tripped from
    /// storage).
    pub fn from_bytes(bytes: [u8; 32]) -> Self {
        OpaqueRoute(bytes)
    }

    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }
}

/// Coarse, bucketed storage metadata — deliberately not an exact
/// application-chosen expiry, which could fingerprint content class the
/// same way an exact payload length can (see this module's own doc note).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
pub enum RetentionClass {
    /// Short-lived; a storage node may discard this quickly.
    Ephemeral,
    /// Ordinary retention (the default assumption absent other policy).
    Standard,
    /// Long-term/archival retention.
    Archival,
}

impl RetentionClass {
    fn tag(self) -> u8 {
        match self {
            RetentionClass::Ephemeral => 0,
            RetentionClass::Standard => 1,
            RetentionClass::Archival => 2,
        }
    }

    fn from_tag(tag: u8) -> Result<Self> {
        match tag {
            0 => Ok(RetentionClass::Ephemeral),
            1 => Ok(RetentionClass::Standard),
            2 => Ok(RetentionClass::Archival),
            _ => Err(ObjectError::BadObject),
        }
    }
}

/// Bounded, blind-storage-facing metadata about the envelope.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StorageDescriptor {
    pub retention: RetentionClass,
}

/// The public outer envelope. See the module docs for exactly what does
/// and does not remain visible.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObjectEnvelopeV2 {
    id: ObjectId,
    suite: AeadSuite,
    route: OpaqueRoute,
    storage: StorageDescriptor,
    nonce: AeadNonce,
    ciphertext: Vec<u8>,
}

impl ObjectEnvelopeV2 {
    /// The content id, over the canonical full outer bytes (`BLAKE3`
    /// multihash, matching v1's `ObjectId::of` exactly — same recipe,
    /// same tamper-evidence/deduplication properties).
    pub fn id(&self) -> &ObjectId {
        &self.id
    }

    pub fn suite(&self) -> AeadSuite {
        self.suite
    }

    pub fn route(&self) -> OpaqueRoute {
        self.route
    }

    pub fn storage(&self) -> StorageDescriptor {
        self.storage
    }

    /// Encrypt `inner` under `key`, with a fresh random nonce. Random
    /// nonces (rather than a deterministic/counter scheme) are
    /// deliberate here: identical plaintext sealed twice must produce
    /// different ciphertext and different envelope ids, or an observer
    /// could confirm two private objects are equal without decrypting
    /// either — a confirmation attack this design exists to prevent (see
    /// module docs).
    pub fn seal(
        inner: &PrivateObject,
        key: &AeadKey,
        route: OpaqueRoute,
        storage: StorageDescriptor,
    ) -> Result<Self> {
        let nonce = AeadNonce::generate().map_err(ObjectError::Crypto)?;
        let suite = key.suite();
        let aad = header_bytes(suite, &route, storage, &nonce);
        let ciphertext = key
            .encrypt(&nonce, &inner.to_bytes(), &aad)
            .map_err(ObjectError::Crypto)?;
        let mut env = ObjectEnvelopeV2 {
            id: ObjectId::of(b""), // placeholder, replaced below
            suite,
            route,
            storage,
            nonce,
            ciphertext,
        };
        env.id = ObjectId::of(&env.to_bytes());
        Ok(env)
    }

    /// Decrypt and parse the inner private object. Fails if `key` is
    /// wrong, if any public field was tampered with (all are bound as
    /// AEAD associated data), or if the decrypted bytes don't parse as a
    /// well-formed [`PrivateObject`].
    pub fn open(&self, key: &AeadKey) -> Result<PrivateObject> {
        let aad = header_bytes(self.suite, &self.route, self.storage, &self.nonce);
        let plaintext = key
            .decrypt(&self.nonce, &self.ciphertext, &aad)
            .map_err(ObjectError::Crypto)?;
        PrivateObject::from_bytes(&plaintext)
    }

    /// Canonical full outer bytes — what the id is derived from and what
    /// travels/is stored. Never includes the id itself (content-addressed,
    /// same convention as v1).
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut w = Writer::new();
        w.raw(&header_bytes(
            self.suite,
            &self.route,
            self.storage,
            &self.nonce,
        ));
        w.bytes(&self.ciphertext);
        w.into_bytes()
    }

    /// Decode an envelope from untrusted bytes. Rejects a non-`2` version
    /// byte, an unknown suite, an over-cap ciphertext length (checked
    /// before allocating), and any trailing bytes.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        let mut r = Reader::new(bytes);
        if r.u8()? != ENVELOPE_VERSION {
            return Err(ObjectError::UnsupportedEnvelopeVersion);
        }
        let suite = AeadSuite::from_tag(r.u8()?).map_err(ObjectError::Crypto)?;
        let route_bytes: [u8; 32] = r
            .raw(32)?
            .try_into()
            .expect("Reader::raw(32) always returns exactly 32 bytes");
        let route = OpaqueRoute::from_bytes(route_bytes);
        let retention = RetentionClass::from_tag(r.u8()?)?;
        let storage = StorageDescriptor { retention };
        let nonce_bytes: [u8; 12] = r
            .raw(suite.nonce_len())?
            .try_into()
            .expect("Reader::raw(nonce_len) always returns exactly nonce_len bytes");
        let nonce = AeadNonce::from_bytes(&nonce_bytes).map_err(ObjectError::Crypto)?;
        let ciphertext = r.bytes_limited(MAX_CIPHERTEXT_BYTES)?;
        if !r.finished() {
            return Err(ObjectError::TrailingBytes);
        }
        let mut env = ObjectEnvelopeV2 {
            id: ObjectId::of(b""),
            suite,
            route,
            storage,
            nonce,
            ciphertext,
        };
        env.id = ObjectId::of(&env.to_bytes());
        Ok(env)
    }

    /// Confirm `claimed` names exactly these bytes. Any holder can check
    /// this with no key at all — the same integrity layer v1 offers via
    /// `Object::verify_integrity`.
    pub fn verify_integrity(&self, claimed: &ObjectId) -> Result<()> {
        if &self.id == claimed {
            Ok(())
        } else {
            Err(ObjectError::IdMismatch)
        }
    }
}

/// The public header bytes: everything except ciphertext, bound as AEAD
/// associated data so an attacker cannot change routing, suite, or
/// retention semantics without causing decryption to fail.
fn header_bytes(
    suite: AeadSuite,
    route: &OpaqueRoute,
    storage: StorageDescriptor,
    nonce: &AeadNonce,
) -> Vec<u8> {
    let mut w = Writer::new();
    w.u8(ENVELOPE_VERSION);
    w.u8(suite.tag());
    w.raw(route.as_bytes());
    w.u8(storage.retention.tag());
    w.raw(nonce.as_bytes());
    w.into_bytes()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::object::{Link, ObjectType};
    use did_mini::Controller;

    fn sample_inner() -> PrivateObject {
        let device = Controller::incept_single().unwrap();
        PrivateObject::new(
            ObjectType::POST,
            device.did(),
            device.did(),
            1_000,
            1,
            vec![Link {
                rel: "re".to_string(),
                target: ObjectId::of(b"linked"),
            }],
            b"meta".to_vec(),
            b"a private reply".to_vec(),
        )
        .sign_with(&device)
    }

    fn sample_storage() -> StorageDescriptor {
        StorageDescriptor {
            retention: RetentionClass::Standard,
        }
    }

    #[test]
    fn a_sealed_envelope_opens_back_to_the_same_inner_object() {
        let inner = sample_inner();
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let env = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage()).unwrap();
        let opened = env.open(&key).unwrap();
        assert_eq!(opened, inner);
    }

    #[test]
    fn a_sealed_envelope_round_trips_through_wire_bytes() {
        let inner = sample_inner();
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let env = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage()).unwrap();
        let decoded = ObjectEnvelopeV2::from_bytes(&env.to_bytes()).unwrap();
        assert_eq!(decoded, env);
    }

    #[test]
    fn a_v1_object_is_rejected_by_the_v2_parser() {
        // v1's first byte is always 1; v2 requires exactly 2.
        let v1_like = [1u8, 0, 0, 0];
        assert_eq!(
            ObjectEnvelopeV2::from_bytes(&v1_like),
            Err(ObjectError::UnsupportedEnvelopeVersion)
        );
    }

    #[test]
    fn a_v2_envelope_is_rejected_by_the_v1_parser() {
        let inner = sample_inner();
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let env = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage()).unwrap();
        assert!(crate::Object::from_bytes(&env.to_bytes()).is_err());
    }

    #[test]
    fn tampering_with_the_route_breaks_decryption() {
        let inner = sample_inner();
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let mut env = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage()).unwrap();
        let mut tampered_route = *env.route.as_bytes();
        tampered_route[0] ^= 0xff;
        env.route = OpaqueRoute::from_bytes(tampered_route);
        assert!(env.open(&key).is_err());
    }

    #[test]
    fn tampering_with_retention_breaks_decryption() {
        let inner = sample_inner();
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let mut env = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage()).unwrap();
        env.storage.retention = RetentionClass::Archival;
        assert!(env.open(&key).is_err());
    }

    #[test]
    fn tampering_with_one_ciphertext_byte_breaks_decryption() {
        let inner = sample_inner();
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let mut env = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage()).unwrap();
        env.ciphertext[0] ^= 0xff;
        assert!(env.open(&key).is_err());
    }

    #[test]
    fn the_wrong_key_cannot_open_the_envelope() {
        let inner = sample_inner();
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let wrong_key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let env = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage()).unwrap();
        assert!(env.open(&wrong_key).is_err());
    }

    #[test]
    fn identical_inner_objects_sealed_twice_produce_different_ciphertext_and_ids() {
        let inner = sample_inner();
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let a = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage()).unwrap();
        let b = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage()).unwrap();
        assert_ne!(a.to_bytes(), b.to_bytes());
        assert_ne!(a.id(), b.id());
    }

    #[test]
    fn the_outer_bytes_contain_none_of_the_private_fields() {
        let device = Controller::incept_single().unwrap();
        let did_bytes = device.did().as_str().as_bytes().to_vec();
        let inner = PrivateObject::new(
            ObjectType::Custom("secret-type-name".to_string()),
            device.did(),
            device.did(),
            42,
            7,
            vec![],
            b"application secret metadata".to_vec(),
            b"the actual private content".to_vec(),
        )
        .sign_with(&device);
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let env = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage()).unwrap();
        let outer = env.to_bytes();
        // The ciphertext is opaque, but scan the whole outer encoding (as
        // random ChaCha20-Poly1305 output it should never coincidentally
        // contain these needles) to guard against any accidental plaintext
        // leak in the public header fields.
        assert!(!contains(&outer, &did_bytes));
        assert!(!contains(&outer, b"secret-type-name"));
        assert!(!contains(&outer, b"application secret metadata"));
        assert!(!contains(&outer, b"the actual private content"));
    }

    fn contains(haystack: &[u8], needle: &[u8]) -> bool {
        haystack.windows(needle.len()).any(|w| w == needle)
    }

    #[test]
    fn a_truncated_envelope_is_rejected_at_every_length() {
        let inner = sample_inner();
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let full = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage())
            .unwrap()
            .to_bytes();
        for cut in 0..full.len() {
            assert!(
                ObjectEnvelopeV2::from_bytes(&full[..cut]).is_err(),
                "truncating to {cut} bytes must be rejected"
            );
        }
    }

    #[test]
    fn trailing_bytes_are_rejected() {
        let inner = sample_inner();
        let key = AeadKey::generate(AeadSuite::DEFAULT).unwrap();
        let route = OpaqueRoute::random().unwrap();
        let mut bytes = ObjectEnvelopeV2::seal(&inner, &key, route, sample_storage())
            .unwrap()
            .to_bytes();
        bytes.push(0xff);
        assert_eq!(
            ObjectEnvelopeV2::from_bytes(&bytes),
            Err(ObjectError::TrailingBytes)
        );
    }

    #[test]
    fn an_unknown_suite_tag_is_rejected() {
        let mut w = Writer::new();
        w.u8(ENVELOPE_VERSION);
        w.u8(0xee); // not a known AeadSuite tag
        assert!(matches!(
            ObjectEnvelopeV2::from_bytes(&w.into_bytes()),
            Err(ObjectError::Crypto(_))
        ));
    }

    #[test]
    fn an_unknown_retention_tag_is_rejected() {
        let mut w = Writer::new();
        w.u8(ENVELOPE_VERSION);
        w.u8(AeadSuite::DEFAULT.tag());
        w.raw(&[0u8; 32]);
        w.u8(0xee); // not a known RetentionClass tag
        assert_eq!(
            ObjectEnvelopeV2::from_bytes(&w.into_bytes()),
            Err(ObjectError::BadObject)
        );
    }

    #[test]
    fn an_over_cap_ciphertext_length_is_rejected_before_allocating() {
        let mut w = Writer::new();
        w.u8(ENVELOPE_VERSION);
        w.u8(AeadSuite::DEFAULT.tag());
        w.raw(&[0u8; 32]);
        w.u8(RetentionClass::Standard.tag());
        w.raw(&[0u8; 12]);
        w.u32((MAX_CIPHERTEXT_BYTES as u32) + 1);
        assert_eq!(
            ObjectEnvelopeV2::from_bytes(&w.into_bytes()),
            Err(ObjectError::LimitExceeded)
        );
    }
}
