#!/usr/bin/env bash
# Mininet Node Appliance — resolve packages.lock against a real mirror.
#
# `deploy/packages.lock` as checked in is a DECLARED REQUIREMENT SET: names,
# no versions. That is honest but weak — two machines provisioned a month
# apart get different package versions, so "a known Mininet node" is only
# known up to whatever Debian Stable shipped that day.
#
# This script is the other half: run it on a real Debian Stable machine (or
# against a mirror snapshot) and it emits a version-pinned lock. It never
# hand-authors a pin, because a pin nobody resolved against an actual
# archive is worse than no pin — it looks precise and is fiction.
#
# Usage:
#   deploy/verification/lock-packages.sh                 # print to stdout
#   deploy/verification/lock-packages.sh --write         # rewrite packages.lock.resolved
#   deploy/verification/lock-packages.sh --check         # fail if resolved file is stale
#
# The output goes to `packages.lock.resolved`, NOT to `packages.lock`. The
# requirement set is human-authored and reviewed; the resolved pins are
# machine-generated and architecture-specific. Conflating them would mean a
# reviewer could no longer see which packages were deliberately chosen.
#
# What this does not do: verify signatures or hashes of the packages
# themselves. Debian's own apt does that with its archive keyring, and
# reimplementing it here would be inventing a second, worse trust path
# (see docs/design/mininet-node-appliance.md's honest non-claims).

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
DEPLOY_ROOT="$(dirname -- "${SCRIPT_DIR}")"
LOCK="${DEPLOY_ROOT}/packages.lock"
RESOLVED="${DEPLOY_ROOT}/packages.lock.resolved"

MODE="print"
for arg in "$@"; do
    case "${arg}" in
        --write) MODE="write" ;;
        --check) MODE="check" ;;
        *) printf 'unknown argument: %s\n' "${arg}" >&2; exit 1 ;;
    esac
done

if ! command -v apt-cache >/dev/null 2>&1; then
    printf 'lock-packages: apt-cache not found; run this on a Debian/apt host\n' >&2
    exit 1
fi

if [[ ! -r "${LOCK}" ]]; then
    printf 'lock-packages: %s not readable\n' "${LOCK}" >&2
    exit 1
fi

arch="$(dpkg --print-architecture 2>/dev/null || echo unknown)"
# shellcheck disable=SC1091 # runtime file, not resolvable at lint time
codename="$(. /etc/os-release 2>/dev/null && printf '%s' "${VERSION_CODENAME:-unknown}")"

emit() {
    printf '# Mininet Node Appliance — RESOLVED package pins.\n'
    printf '#\n'
    printf '# Generated by deploy/verification/lock-packages.sh. Do not hand-edit:\n'
    printf '# every line here was resolved against a real archive, and editing one\n'
    printf '# by hand produces a pin that no mirror ever offered.\n'
    printf '#\n'
    printf '# architecture: %s\n' "${arch}"
    printf '# suite:        %s\n' "${codename}"
    printf '#\n'
    printf '# Pins are architecture- and suite-specific. A resolved file from an\n'
    printf '# amd64 box does not describe an arm64 node; generate one per target.\n'
    printf '\n'

    local unresolved=0
    while read -r package; do
        [[ -n "${package}" ]] || continue
        # Strip any pre-existing "=version" so this is re-runnable.
        package="${package%%=*}"
        local version
        version="$(apt-cache policy "${package}" 2>/dev/null \
            | awk '/^  Candidate:/ { print $2; exit }')"
        if [[ -z "${version}" || "${version}" == "(none)" ]]; then
            printf '# UNRESOLVED on %s/%s: %s\n' "${arch}" "${codename}" "${package}"
            unresolved=$((unresolved + 1))
        else
            printf '%s=%s\n' "${package}" "${version}"
        fi
    done < <(grep -v '^\s*#' "${LOCK}" | grep -v '^\s*$' | tr -d ' \t')

    if [[ "${unresolved}" -gt 0 ]]; then
        printf '\n# %d package(s) did not resolve on this host. A node built from this\n' "${unresolved}"
        printf '# file would be missing them; fix the requirement set or the mirror\n'
        printf '# rather than shipping a lock with holes in it.\n'
    fi
}

case "${MODE}" in
    print)
        emit
        ;;
    write)
        emit > "${RESOLVED}"
        printf 'lock-packages: wrote %s (%s/%s)\n' "${RESOLVED}" "${arch}" "${codename}" >&2
        ;;
    check)
        if [[ ! -r "${RESOLVED}" ]]; then
            printf 'lock-packages: %s does not exist; run --write on a Debian host\n' "${RESOLVED}" >&2
            exit 1
        fi
        if diff -u "${RESOLVED}" <(emit) >/dev/null; then
            printf 'lock-packages: %s is current for %s/%s\n' "${RESOLVED}" "${arch}" "${codename}" >&2
        else
            printf 'lock-packages: %s is stale for %s/%s:\n' "${RESOLVED}" "${arch}" "${codename}" >&2
            diff -u "${RESOLVED}" <(emit) >&2 || true
            exit 1
        fi
        ;;
esac
