#!/usr/bin/env python3
"""Collapse nested availability matches generated by the stable-provider helper."""
from pathlib import Path

path = Path("crates/mini-search-federation-net/src/query.rs")
text = path.read_text(encoding="utf-8")
old = '''fn validate_availability(availability: &AvailabilityState) -> Result<()> {
    match availability {
        AvailabilityState::Available => Ok(()),
        AvailabilityState::Unavailable(reason) => match reason {
            UnavailabilityReason::NotFetched
            | UnavailabilityReason::FetchFailed
            | UnavailabilityReason::Gone
            | UnavailabilityReason::UnsupportedContent => Ok(()),
            _ => Err(NetError::Protocol),
        },
        AvailabilityState::Restricted(reason) => match reason {
            RestrictionReason::LegalRestriction { jurisdiction } => {
                if jurisdiction.len() > MAX_JURISDICTION_BYTES {
                    Err(NetError::LimitExceeded)
                } else {
                    Ok(())
                }
            }
            RestrictionReason::RobotsExcluded
            | RestrictionReason::Malware
            | RestrictionReason::Spam
            | RestrictionReason::UserFilter
            | RestrictionReason::SafetyWarning => Ok(()),
            _ => Err(NetError::Protocol),
        },
        _ => Err(NetError::Protocol),
    }
}
'''
new = '''fn validate_availability(availability: &AvailabilityState) -> Result<()> {
    match availability {
        AvailabilityState::Available
        | AvailabilityState::Unavailable(
            UnavailabilityReason::NotFetched
            | UnavailabilityReason::FetchFailed
            | UnavailabilityReason::Gone
            | UnavailabilityReason::UnsupportedContent,
        )
        | AvailabilityState::Restricted(
            RestrictionReason::RobotsExcluded
            | RestrictionReason::Malware
            | RestrictionReason::Spam
            | RestrictionReason::UserFilter
            | RestrictionReason::SafetyWarning,
        ) => Ok(()),
        AvailabilityState::Restricted(RestrictionReason::LegalRestriction {
            jurisdiction,
        }) => {
            if jurisdiction.len() > MAX_JURISDICTION_BYTES {
                Err(NetError::LimitExceeded)
            } else {
                Ok(())
            }
        }
        AvailabilityState::Unavailable(_) | AvailabilityState::Restricted(_) => {
            Err(NetError::Protocol)
        }
        _ => Err(NetError::Protocol),
    }
}
'''
if text.count(old) != 1:
    raise SystemExit(f"expected one generated availability validator, found {text.count(old)}")
path.write_text(text.replace(old, new), encoding="utf-8")
print("PR 296 stable-provider Clippy correction applied")
